#本地环境
spring:
  #应用信息
  application:
    name: user-consumer
  #数据源配置
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/sky?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: root
    redis:
      host: 127.0.0.1
      port: 6379

#服务端口号
server:
  port: 9002

#eureka服务与发现注册中心地址   
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/

