#数据源配置 
spring:
  datasource:
    url: jdbc:mysql://119.23.208.37:3306/sky?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: Hebs8169816~!@
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximumPoolSize: 15
  redis:
    host: 127.0.0.1
    port: 6379
  #web容器undertow优化配置
  undertow:
    io-threads: 8
    worker-threads: 40
    buffer-size: 512
    buffers-per-region: 10
    direct-buffers: true
    
#开源通用mapper
mapper:
  mappers:
  - com.sky.base.BaseMapper
  not-empty: false
  identity: MYSQL
  style: normal #数据库字段与实体类属性映射方式,详情见tk.mybatis.mapper.code.Style 

#mybatis配置
mybatis:
  type-aliases-package: com.sky.*.pojo
  mapper-locations:
  - classpath*:com/sky/**/mapping/*Mapper.xml

#分页助手
pagehelper:
  helper-dialect : mysql
  support-methods-arguments: true
  params: countSql 
  reasonable : false
  
#jwt相关配置     
jwt:
  #jwt请求头
  header : token
  #jwt token 前缀:持票人,可以自定义
  prefix : Bearer
  #秘钥bingsen.he的base64编码
  secret : YmluZ3Nlbi5oZQ==
  #有效期(单位:秒) 30*60=1800
  expiration : 1800